### ISSUE TITLE
Respect protected areas

### ISSUE THREAD

**Issue by kyleclaassen** [kyleclaassen/minetest_mathplot#18]
Check minetest.is_protected() in so that mathplot doesn't trespass into protected areas.

**Comment by FirePowi** [comment]
[Fixed](431f848)

**Comment by FirePowi** [comment]
Commit: [431f848](https://github.com/kyleclaassen/minetest_mathplot/commit/431f848f788d4cd02303a90d26ec38a7bb8e9952)

**Comment by kyleclaassen** [comment]
Huge performance hit. Some of the implicit plot examples (e.g. Cylinder w/ Tunnel) timeout when is_protected() is checked. Without, the same examples finish in less than a second.

**Comment by kyleclaassen** [comment]
To help avoid the potential for performance issues if minetest.is_protected() is costly, protection checks are disabled by default. In the most likely use-case, protection checks aren't necessary anyway.

Protection checks can be enabled in-game with "/mathplot respect_protected_areas true".

There is also a default setting mathplot.respect_protected_areas that can be toggled at the Minetest "All Settings" screen.

Protection checks will be ignored if the user has the protection_bypass privilege.

Fixed by commit 8986358845b27e3f435ee3106167e1058f25546c.

**Comment by kyleclaassen** [comment]
Also fixed the "/mathplot setorigin" command to respect protected areas.

See commit 338a7a0a85c44584c66348c421275c5ef14153d3.
